### ISSUE TITLE
check if PR already exists

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#12] opened 2018-06-15 08:45 UTC
As Kebechet
I want to check if a PR that I want to open already exists,
so that I do not open a PR twice: one closed and one new opened.

**Comment by fridex** [comment] 2018-06-16 00:30
This should be handled by design. Was this encountered somewhere?

**Comment by fridex** [comment] 2018-06-28 05:06
I will close this. If you feel this is still an issue, feel free to reopen.

**Closed by fridex** 2018-06-28 05:06 UTC
Labels: bug, enhancement
